### ISSUE TITLE
Size of nodes are not considered when arranging nodes

### ISSUE THREAD

**Issue by cmbasnett** [Leonardo-Pike-Excell/node-arrange#2]
The wide & tall image node here is not properly considered when ensuring minimum spacing between nodes.

![image](https://github.com/user-attachments/assets/49656b53-b058-410b-ae95-929a4f3bcc92)

**Comment by Leonardo-Pike-Excell** [comment]
Hi, thanks for the report. Could you share the resolution scale found in preferences > interface?

**Comment by cmbasnett** [comment]
![image](https://github.com/user-attachments/assets/18097d90-dc15-406d-9d69-4d19d212ebf6)

I also tried it with a resolution scale of 1.0 and the same issue persisted.

**Comment by Leonardo-Pike-Excell** [comment]
Would you be able to share the node tree?
