### ISSUE TITLE
The arrange is not at all suitable for working with frames.

### ISSUE THREAD

**Issue by ugorek000** [Leonardo-Pike-Excell/node-arrange#7]
:-1::-1:🤢
![2024-09-23_04 41 48](https://github.com/user-attachments/assets/89ebef42-f402-4f91-b9dc-1c08b1527b51)

**Comment by Leonardo-Pike-Excell** [comment]
Could you provide the node tree?

**Comment by ugorek000** [comment]
[24.09.23  10.01.58.blend.txt](https://github.com/user-attachments/files/17092336/24.09.23.10.01.58.blend.txt)
